[package]
name = "mli_mep"
version = "0.9.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]

[dependencies]
rand = "0.3.13"
num = "0.1.30"
serde = "0.8"
serde_derive = "0.8"
mli = {git = "https://github.com/vadixidav/mli"}
